# This is a basic workflow to help you get started with Actions

name: Test Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "working" ]
  pull_request:
    branches: [ "working" , "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Install dependencies:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Install git
       run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install git -y


      # Runs a single command using the runners shell
      - name: Clone repository
        run: git clone -b working https://git.bitsyncdev.com/bit-sync/Poss-v2.git

  run code:
   runs-on: ubuntu-latest
   steps:
    - name: Install poss
      run: |
       sudo apt install pip -y
       pip install setuptools
       pip install setuptools --break-system-packages
       cd Poss-v2
       sudo python3 setup.py develop
    - name: Test Poss commands
     run: |
       poss version

