# This is a basic workflow to help you get started with Actions

name: Test Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
     # - name: print hello
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install Poss
        run: curl -fsSL https://git.bitsyncdev.com/bit-sync/Poss-v2/raw/branch/install/install.sh | sudo bash
      - name: Run Poss
        run: |
         poss version
         poss install pycalculate
         poss uninstall pycalculate
 # deploy:
  # runs-on: ubuntu-latest
 #  steps:
  #  - uses: actions/checkout@v2
#    - name: deploy
   #   run: |
   #    apt install curl -y
  #     curl https://git.bitsyncdev.com       